# Generated by Django 1.11.20 on 2019-02-26 12:19


from django.db import migrations

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(user_last_name__isnull=True).update(user_last_name='')
    Profile.objects.filter(user_first_name__isnull=True).update(user_first_name='')
    Profile.objects.filter(user_middle_name__isnull=True).update(user_middle_name='')

    CustomerProfile = apps.get_model('users', 'CustomerProfile')
    CustomerProfile.objects.filter(user_last_name__isnull=True).update(user_last_name='')
    CustomerProfile.objects.filter(user_first_name__isnull=True).update(user_first_name='')
    CustomerProfile.objects.filter(user_middle_name__isnull=True).update(user_middle_name='')

    BankAccount = apps.get_model('users', 'BankAccount')
    BankAccount.objects.filter(ls__isnull=True).update(ls='')

    RegisterProfile = apps.get_model('users', 'RegisterProfile')
    RegisterProfile.objects.filter(user_middle_name__isnull=True).update(user_middle_name='')

    BankAccountRegister = apps.get_model('users', 'BankAccountRegister')
    BankAccountRegister.objects.filter(ls__isnull=True).update(ls='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190114_1736'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
