# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import pd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_not_null_charfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='ls',
            field=models.CharField(blank=True, default=b'', max_length=11, validators=[pd.utils.LengthValidator(11)], verbose_name='\u041b/\u0441'),
        ),
        migrations.AlterField(
            model_name='bankaccountregister',
            name='ls',
            field=models.CharField(blank=True, default=b'', max_length=11, validators=[pd.utils.LengthValidator(11)], verbose_name='\u041b/\u0441'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user_first_name',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user_last_name',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user_middle_name',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_first_name',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_last_name',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_middle_name',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='user_middle_name',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e (\u043d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)'),
        ),
    ]
