# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190226_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('title',), 'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
