# Generated by Django 2.2.6 on 2019-10-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190916_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dover',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'is_agent': True}, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(blank=True, default=False, verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='out_of_staff',
            field=models.BooleanField(blank=True, default=False, verbose_name='Внештатный сотрудник'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phones_publish',
            field=models.BooleanField(blank=True, default=False, verbose_name='Публиковать телефоны?'),
        ),
        migrations.AlterField(
            model_name='profileloru',
            name='loru',
            field=models.ForeignKey(limit_choices_to={'type': 'loru'}, on_delete=django.db.models.deletion.CASCADE, related_name='ugh_list', to='users.Org', verbose_name='ЛОРУ'),
        ),
        migrations.AlterField(
            model_name='profileloru',
            name='ugh',
            field=models.ForeignKey(limit_choices_to={'type': 'ugh'}, on_delete=django.db.models.deletion.CASCADE, related_name='loru_list', to='users.Org', verbose_name='ОМС'),
        ),
    ]
