# Generated by Django 4.2.4 on 2024-05-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191028_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubecaptionvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='youtubecaptionvote',
            name='youtubecaption',
        ),
        migrations.RemoveField(
            model_name='youtubevote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='youtubevote',
            name='youtubevideo',
        ),
        migrations.DeleteModel(
            name='YoutubeCaption',
        ),
        migrations.DeleteModel(
            name='YoutubeCaptionVote',
        ),
        migrations.DeleteModel(
            name='YoutubeVideo',
        ),
        migrations.DeleteModel(
            name='YoutubeVote',
        ),
    ]
