# Generated by Django 2.2.6 on 2020-09-15 14:24

from django.db import migrations
from django.db.models.query_utils import Q

from logs.models import LogOperation

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Перевести создание заказа в код операции
    """
    print('\n', 'Filling create order operation in Log')
    num = 0
    Log = apps.get_model('logs', 'Log')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    order_ct = ContentType.objects.get(app_label='orders', model='order')
    qs = Q(ct=order_ct) & (Q(msg='Заказ сохранен') | Q(msg='Заказ создан'))
    cur_id = -1
    for l in Log.objects.filter(qs).order_by('dt'):
        if cur_id != l.obj_id:
            cur_id = l.obj_id
            l.msg = ''
            l.operation = LogOperation.ORDER_CREATED
            l.save(update_fields=('msg', 'operation',))
            num += 1
    print ('%s order creation recs in log saved' % num)

class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20181129_1401'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
