# Generated by Django 2.2.6 on 2019-10-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181129_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_agent': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent_director',
            field=models.BooleanField(blank=True, default=False, verbose_name='Директор-Агент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='По умолчанию'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stockable',
            field=models.BooleanField(blank=True, default=True, verbose_name='Товар'),
        ),
    ]
