# Generated by Django 2.2.6 on 2020-04-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191028_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dt_paid',
            field=models.DateTimeField(null=True, verbose_name='Дата/время оплаты'),
        ),
    ]
