# Generated by Django 2.2.6 on 2020-04-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_data_fill_order_dt_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dt_paid',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Дата/время оплаты'),
        ),
    ]
