# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-22 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20190916_1724'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название зала')),
                ('time_start', models.CharField(blank=True, max_length=255, verbose_name='Начало работы')),
                ('time_end', models.CharField(blank=True, max_length=255, verbose_name='Окончание работы')),
                ('interval', models.PositiveIntegerField(choices=[(10, '10'), (15, '15'), (20, '20'), (30, '30'), (60, '60')], default=30, verbose_name='Минимальное время, минуты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Org', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ('org', 'title'),
            },
        ),
        migrations.CreateModel(
            name='HallTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_start', models.DateTimeField(verbose_name='Время начала')),
                ('dt_end', models.DateTimeField(verbose_name='Время окончания')),
                ('details', models.TextField(blank=True, verbose_name='Примечания')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.Hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Назначенное время в зале',
                'verbose_name_plural': 'Расписание залов',
            },
        ),
        migrations.AlterUniqueTogether(
            name='halltimetable',
            unique_together=set([('hall', 'dt_start', 'dt_end')]),
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together=set([('org', 'title')]),
        ),
    ]
