# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='interval',
            field=models.PositiveIntegerField(choices=[(10, ' 10'), (15, ' 15'), (20, ' 20'), (30, ' 30'), (40, ' 40'), (60, ' 60'), (120, '120')], default=30, verbose_name='Минимальное время, минуты'),
        ),
    ]
