# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_auto_20190925_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], default=1, verbose_name='День')),
                ('time_start', models.CharField(blank=True, max_length=255, verbose_name='Начало')),
                ('time_end', models.CharField(blank=True, max_length=255, verbose_name='Окончание')),
                ('interval', models.PositiveIntegerField(choices=[(10, '10 мин.'), (15, '15 мин.'), (20, '20 мин.'), (30, '30 мин.'), (40, '40 мин.'), (60, 'час'), (120, '2 часа')], default=30, verbose_name='Время')),
                ('is_dayoff', models.BooleanField(default=False, verbose_name='Выходной')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.Hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'День недели в зале',
                'verbose_name_plural': 'Дни недели в залах',
            },
        ),
        migrations.AlterUniqueTogether(
            name='hallweekly',
            unique_together=set([('hall', 'dow')]),
        ),
    ]
