# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_data_fill_hall_weekly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallweekly',
            options={'ordering': ('hall', 'dow'), 'verbose_name': 'День недели в зале', 'verbose_name_plural': 'Дни недели в залах'},
        ),
        migrations.RemoveField(
            model_name='hall',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='time_start',
        ),
    ]
