# Generated by Django 2.2.6 on 2020-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0005_auto_20191001_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='halltimetable',
            name='kind',
            field=models.CharField(choices=[('burn', 'Кремация'), ('move', 'Вывоз на захоронение')], default='burn', max_length=10, verbose_name='Тип'),
        ),
    ]
