# Generated by Django 2.2.6 on 2019-10-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20181129_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ugh',
            field=models.ForeignKey(limit_choices_to={'type': 'ugh'}, on_delete=django.db.models.deletion.CASCADE, to='users.Org', verbose_name='ОМС'),
        ),
    ]
