# Generated by Django 1.11.20 on 2019-02-26 11:54


from django.db import migrations

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    PersonID = apps.get_model('persons', 'PersonID')
    PersonID.objects.filter(series__isnull=True).update(series='')
    PersonID.objects.filter(number__isnull=True).update(number='')

    DeathCertificate = apps.get_model('persons', 'DeathCertificate')
    DeathCertificate.objects.filter(series__isnull=True).update(series='')
    DeathCertificate.objects.filter(s_number__isnull=True).update(s_number='')

class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20190114_1736'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
