# Generated by Django 1.11.20 on 2019-02-26 12:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_data_not_null_charfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathcertificate',
            name='s_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='deathcertificate',
            name='series',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u0421\u0435\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='personid',
            name='number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='personid',
            name='series',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u0421\u0435\u0440\u0438\u044f'),
        ),
    ]
