# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-01 14:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burials', '0002_auto_20181129_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grave',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='lng',
        ),
    ]
