# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 11:13
from __future__ import unicode_literals

from django.db import migrations

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    Burial = apps.get_model('burials', 'Burial')
    Burial.objects.filter(account_number__isnull=True).update(account_number='')
    Burial.objects.filter(burial_type__isnull=True).update(burial_type='common')
    Burial.objects.filter(burial_container__isnull=True).update(burial_container='container_coffin')

class Migration(migrations.Migration):

    dependencies = [
        ('burials', '0003_auto_20190201_1411'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
