# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 11:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burials', '0004_data_not_null_charfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burial',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u2116 \u0432 \u043a\u043d\u0438\u0433\u0435 \u0443\u0447\u0435\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='burial_container',
            field=models.CharField(blank=True, choices=[('container_coffin', '\u0413\u0440\u043e\u0431'), ('container_urn', '\u0423\u0440\u043d\u0430'), ('container_ash', '\u041f\u0440\u0430\u0445'), ('container_bio', '\u0411\u0438\u043e\u043e\u0442\u0445\u043e\u0434\u044b')], default='container_coffin', max_length=255, verbose_name='\u0422\u0438\u043f \u0437\u0430\u0445\u043e\u0440\u043e\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='burial_type',
            field=models.CharField(blank=True, choices=[('common', '\u041d\u043e\u0432\u043e\u0435 \u0437\u0430\u0445\u043e\u0440\u043e\u043d\u0435\u043d\u0438\u0435'), ('additional', '\u041f\u043e\u0434\u0437\u0430\u0445\u043e\u0440\u043e\u043d\u0435\u043d\u0438\u0435'), ('overlap', '\u0417\u0430\u0445\u043e\u0440\u043e\u043d\u0435\u043d\u0438\u0435 \u0432 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044e\u0449\u0443\u044e')], default='common', max_length=255, verbose_name='\u0412\u0438\u0434 \u0437\u0430\u0445\u043e\u0440\u043e\u043d\u0435\u043d\u0438\u044f'),
        ),
    ]
