# Generated by Django 2.2.6 on 2019-10-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burials', '0005_auto_20190226_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burial',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_agent': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_burials', to='users.Profile', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='agent_director',
            field=models.BooleanField(blank=True, default=False, verbose_name='Директор-Агент'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='annulated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Аннулировано'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='loru',
            field=models.ForeignKey(limit_choices_to={'type': 'loru'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Org', verbose_name='Посредник'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='loru_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_agent': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loru_agent_burials', to='users.Profile', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='loru_agent_director',
            field=models.BooleanField(blank=True, default=False, verbose_name='Директор-Агент'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='ugh',
            field=models.ForeignKey(editable=False, limit_choices_to={'type': 'ugh'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ugh_created', to='users.Org', verbose_name='УГХ'),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='ugh',
            field=models.ForeignKey(limit_choices_to={'type': 'ugh'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Org', verbose_name='УГХ'),
        ),
        migrations.AlterField(
            model_name='exhumationrequest',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_agent': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='exhumationrequest',
            name='agent_director',
            field=models.BooleanField(blank=True, default=False, verbose_name='Директор-Агент'),
        ),
    ]
